name: jack_rtc_call
description: Package for WebRTC and Callkit
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_callkit_incoming: ^2.0.0+1
  flutter_webrtc: ^0.9.34
  rxdart: ^0.27.7
  socket_io_client: ^2.0.3+1
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
